<?php
$pdo = getDBConnection();
$id = $_GET['id'] ?? 0;

$stmt = $pdo->prepare("SELECT * FROM categories WHERE id = ?");
$stmt->execute([$id]);
$category = $stmt->fetch();

if (!$category) {
    $_SESSION['error'] = 'Category not found.';
    header('Location: index.php?page=categories');
    exit;
}
?>
<div class="max-w-4xl mx-auto">
    <div class="mb-8">
        <div class="flex items-center gap-4">
            <a href="?page=categories" class="text-gray-600 hover:text-gray-800">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                </svg>
            </a>
            <div>
                <h2 class="text-2xl font-bold text-gray-800 mb-2">Edit Category</h2>
                <p class="text-gray-600">Update category information</p>
            </div>
        </div>
    </div>

    <div class="bg-white rounded-lg border-2 border-gray-300 p-8">
        <form method="POST" action="index.php">
            <input type="hidden" name="edit_category" value="1">
            <input type="hidden" name="category_id" value="<?php echo $category['id']; ?>">
            
            <div class="space-y-6">
                <div>
                    <label class="block text-sm font-semibold text-gray-700 mb-2">Category Name *</label>
                    <input type="text" name="name" id="categoryName" value="<?php echo htmlspecialchars($category['name']); ?>" class="w-full px-4 py-2 border-2 border-gray-300 rounded focus:outline-none focus:border-blue-500" required>
                </div>

                <div>
                    <p class="text-xs text-gray-500 mt-1">Leave empty to auto-generate from name</p>
                </div>

                <div>
                    <label class="block text-sm font-semibold text-gray-700 mb-2">Description</label>
                    <textarea name="description" rows="5" class="w-full px-4 py-2 border-2 border-gray-300 rounded focus:outline-none focus:border-blue-500" placeholder="Enter category description..."><?php echo htmlspecialchars($category['description'] ?? ''); ?></textarea>
                    <p class="text-xs text-gray-500 mt-1">Optional: Brief description of this category</p>
                </div>

                <div>
                    <label class="flex items-center gap-3">
                        <input type="checkbox" name="is_active" value="1" <?php echo $category['is_active'] ? 'checked' : ''; ?> class="w-4 h-4">
                        <span class="text-sm text-gray-700">Active</span>
                    </label>
                    <p class="text-xs text-gray-500 mt-1">Category will be visible on the storefront</p>
                </div>
            </div>

            <div class="mt-6 flex gap-4">
                <button type="submit" class="px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                    Update Category
                </button>
                <a href="?page=categories" class="px-6 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 transition">Cancel</a>
            </div>
        </form>
    </div>
</div>

<script>
document.getElementById('categoryName').addEventListener('input', function() {
    const slugInput = document.getElementById('categorySlug');
    if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        slugInput.value = this.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
        slugInput.dataset.autoGenerated = 'true';
    }
});

document.getElementById('categorySlug').addEventListener('input', function() {
    this.dataset.autoGenerated = 'false';
});
</script>